#!/usr/bin/ruby
require 'json'
require 'rest-client'
require 'colorize'

inputs = ARGV
if inputs[0] == nil || inputs[0] == "-h"
  abort "usage :

  pixelrb FILE_PATH
  author : github.com/polarspetroll".light_cyan
end

filecount = (inputs.length - 1)

for n in 0..filecount
  upload = File.new(inputs[n])
  puts "\nUploading #{inputs[n]}...".light_cyan
  request = RestClient.post 'https://pixeldrain.com/api/file', {file: upload}
  replydata = JSON.parse(request.body)
  if request.code == 201
    puts "Done!".green
  else
    abort replydata["message"].light_red
  end
  puts "#{inputs[n]} : https://pixeldrain.com/u/#{replydata["id"]}".light_green.bold
end
